<?php

namespace AppBundle\Repository;

/**
 * CentroMedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroMedicoRepository extends \Doctrine\ORM\EntityRepository
{
}
